[ClassicExplorerThemeManifest]
; Version of ClassicExplorer theme manifest
ManifestVersion = 1
Name = Windows 98/2000 Theme
Description = A theme matching the Windows 98 and Windows 2000 visual appearances.
Author = Isabella Lulamoon (kawapure)
; Version of the theme itself
Version = 1.0

[Properties]
ThrobberBackground.Color="#000000"
; Watermarks did not exist before Windows XP.
EnableListViewWatermarks=false

[Files]
; Important notice on GoActive, GoInactive bitmaps (backed by shell ImageList):
; the colour format MUST be 24 bit per pixel with a keyed background
; 32bpp will not be visible.
GoActive = Images\go_active.bmp
GoInactive = Images\go_inactive.bmp

ThrobberSmall = Images\throbber_s0.bmp
ThrobberMedium = Images\throbber_s1.bmp
ThrobberLarge = Images\throbber_s2.bmp