[ClassicExplorerThemeManifest]
ManifestVersion = 1 ; Version of ClassicExplorer theme manifest
Name = Windows 98 First Edition Theme
Description = A theme matching the Windows 98 First Edition visual appearance.
Author = Isabella Lulamoon (kawapure)
Version = 1.0 ; Version of the theme itself

[Properties]
ThrobberBackground.Color="#000000"
EnableListViewWatermarks=false ; Watermarks did not exist before Windows XP.

; Windows 98 First Edition had a differently-sized Go button.
GoActive.Width = 18
GoActive.Height = 18
GoInactive.Width = 18
GoInactive.Height = 18