[ClassicExplorerThemeManifest]
; Version of ClassicExplorer theme manifest
ManifestVersion = 1
Name = Windows 98 First Edition Theme
Description = A theme matching the Windows 98 First Edition visual appearance.
Author = Isabella Lulamoon (kawapure)
; Version of the theme itself
Version = 1.0

[Properties]
ThrobberBackground.Color="#000000"
; Watermarks did not exist before Windows XP.
EnableListViewWatermarks=false

; Windows 98 First Edition had a differently-sized Go button.
GoActive.Width = 18
GoActive.Height = 16
GoInactive.Width = 18
GoInactive.Height = 16

[Files]
; Important notice on GoActive, GoInactive bitmaps (backed by shell ImageList):
; the colour format MUST be 24 bit per pixel with a keyed background
; 32bpp will not be visible.
GoActive = Images\go_active.bmp
GoInactive = Images\a.bmp

ThrobberSmall = Images\throbber_s0.bmp
ThrobberMedium = Images\throbber_s1.bmp
ThrobberLarge = Images\throbber_s2.bmp